### ISSUE TITLE
Improve text for Post on Facebook 

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/AACorporateWebsite#44]
If you would post the link to the website in Facebook a message that could be simplified and improved in shown>

![image](https://user-images.githubusercontent.com/9479367/47436457-d3a2b980-d7a6-11e8-8c77-7dee37425e93.png)

**Comment by julian-molina** [comment]
<meta name="description" content="A collective project fostering the rapid-evolution of trading algorithms through trading bots competitions.">
